#!/bin/bash
set -e

echo "--- BasedAI Node Setup: 05 - Creating Runtime Scripts ---"
echo ""
echo "This script will create easy-to-use helper scripts inside the './basednode' directory."
echo ""

# Define the location for the user's runtime scripts
RUNTIME_SCRIPT_DIR="basednode"

# Check if the directory exists
if [ ! -d "$RUNTIME_SCRIPT_DIR" ]; then
    echo "❌ ERROR: The 'basednode' directory does not exist. Cannot create runtime scripts."
    exit 1
fi

# --- Create the start.sh script ---
echo "[+] Creating 'start.sh' with the correct bootnode Peer ID..."
cat > "${RUNTIME_SCRIPT_DIR}/start.sh" << EOF
#!/bin/bash
# This script was generated by the basednode-ops setup.

# Change to the script's directory to ensure paths are correct
cd "\$(dirname "\$0")"

./target/release/basednode \\
    --base-path ./data \\
    --chain ./mainnet1_raw.json \\
    --port 30333 \\
    --ws-port 9944 \\
    --rpc-port 9933 \\
    --rpc-methods Unsafe \\
    --rpc-cors all \\
    --name "MyBasedNode-$(hostname)" \\
    --validator \\
    --bootnodes /dns/mainnet.basedaibridge.com/tcp/30333/p2p/12D3KooWCQy4hiiA9tHxvQ2PPaSY3mUM6NkMnbsYf2v4FKbLAtUh \\
    -lruntime=debug
EOF
chmod +x "${RUNTIME_SCRIPT_DIR}/start.sh"


# --- Create the monitor.sh script ---
echo "[+] Creating 'monitor.sh' for checking node status..."
cat > "${RUNTIME_SCRIPT_DIR}/monitor.sh" << EOF
#!/bin/bash
# This script was generated by the basednode-ops setup.
# It queries the local RPC endpoint to get the node's health and peer info.

echo "--- Querying Node Status ---"
echo "Health and Sync State:"
curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_health"}' http://localhost:9933
echo ""
echo ""
echo "Connected Peers:"
# Use jq for pretty-printing if available, otherwise print raw
if command -v jq &> /dev/null
then
    curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_peers"}' http://localhost:9933 | jq .
else
    curl -s -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_peers"}' http://localhost:9933
fi
echo ""
echo "---------------------------"
EOF
chmod +x "${RUNTIME_SCRIPT_DIR}/monitor.sh"


echo ""
echo "✅ Runtime scripts ('start.sh', 'monitor.sh') created successfully inside the 'basednode' directory."
echo "--------------------------------------------------------"
echo ""
